apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: openfaas
spec:
  type: NodePort
  ports:
   - name: http-grafana
     port: 3000
     protocol: TCP
     targetPort: 3000
     nodePort: 30003
  selector:
    app: grafana