apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: openfaas
spec:
  replicas: 1
  template:
   metadata:
     name: grafana
     labels:
       app: grafana
   spec:
    containers:
     - name: grafana
       image: grafana/grafana:6.6.0
       imagePullPolicy: Always
       ports:
        - containerPort: 3000
  selector:
    matchLabels:
      app: grafana
